"reg delete \"HKLM\\SYSTEM\\ControlSet001\\Services\\EpicOnlineServices\" /f > nul 2>&1"
"reg delete \"HKCU\\SOFTWARE\\Epic Games\" /f > nul 2>&1"
"reg delete \"HKLM\\SYSTEM\\ControlSet001\\Services\\BEService\" /f > nul 2>&1"
"reg delete \"HKLM\\SYSTEM\\ControlSet001\\Services\\BEDaisy\" /f > nul 2>&1"
"reg delete \"HKLM\\SYSTEM\\ControlSet001\\Services\\EasyAntiCheat\" /f > nul 2>&1"
"reg delete \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\BEService\" /f > nul 2>&1"
"reg delete \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\BEDaisy\" /f > nul 2>&1"
"reg delete \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\EasyAntiCheat\" /f > nul 2>&1"
"reg delete \"HKLM\\SOFTWARE\\WOW6432Node\\EasyAntiCheat\" /f > nul 2>&1"
"reg delete \"HKLM\\SOFTWARE\\WOW6432Node\\Epic Games\" /f > nul 2>&1"
"reg delete \"HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\CapabilityAccessManager\\ConsentStore\\microphone\\NonPackaged\" /f > nul 2>&1"
"reg delete \"HKCU\\Software\\Microsoft\\Windows\\Shell\\Associations\\UrlAssociations\\com.epicgames.launcher\" /f > nul 2>&1"
"reg delete \"HKCR\\com.epicgames.eos\" /f > nul 2>&1"
"reg delete \"HKLM\\SOFTWARE\\Microsoft\\RADAR\\HeapLeakDetection\\DiagnosedApplications\" /f > nul 2>&1"
"reg delete \"HKEY_USERS\\S-1-5-18\\Software\\Epic Games\" /f > nul 2>&1"
"RMDIR /S /Q \"%systemdrive%\\Users\\%username%\\AppData\\Local\\EpicGamesLauncher\" > nul 2>&1"
"RMDIR /S /Q \"%systemdrive%\\Users\\%username%\\AppData\\Local\\FortniteGame\" > nul 2>&1"
"RMDIR /S /Q \"%systemdrive%\\Users\\%username%\\AppData\\Local\\Epic Games\" > nul 2>&1"
"RMDIR /S /Q \"%systemdrive%\\Users\\%username%\\AppData\\Local\\NVIDIA Corporation\" > nul 2>&1"
"RMDIR /S /Q \"%systemdrive%\\Users\\All Users\\Epic\\EpicGamesLauncher\\Data\\EMS\\current\" > nul 2>&1"
"RMDIR /S /Q \"%systemdrive%\\Users\\%username%\\AppData\\Local\\UnrealEngine\" > nul 2>&1"
"RMDIR /S /Q \"%systemdrive%\\ProgramData\\Epic\\EpicOnlineServices\" > nul 2>&1"
"RMDIR /S /Q \"%systemdrive%\\ProgramData\\Epic\\EpicGamesLauncher\\Data\\EMS\\current\" > nul 2>&1"
"RMDIR /S /Q \"%systemdrive%\\Program Files (x86)\\Epic Games\\Epic Online Services\\service\" > nul 2>&1"
"RMDIR /S /Q \"%systemdrive%\\Program Files\\Epic Games\\Fortnite\\FortniteGame\\Binaries\\Win64\\Shared Files\" > nul 2>&1"
"RMDIR /S /Q \"%systemdrive%\\Program Files (x86)\\Common Files\\BattlEye\" > nul 2>&1"
"RMDIR /S /Q \"%systemdrive%\\Program Files (x86)\\EasyAntiCheat\" > nul 2>&1"
"RMDIR /s /Q \"%systemdrive%\\$Recycle.bin\" > nul 2>&1"
"el /q \"%systemdrive%\\ProgramData\\Microsoft\\Windows\\WER\\Temp\\\" > nul 2>&1"
"for /d %x in (\"%systemdrive%\\ProgramData\\Microsoft\\Windows\\WER\\Temp\\*\") do @rd /s /q \"%x\" > nul 2>&1"
"del /q \"%systemdrive%\\Users\\%username%\\AppData\\Local\\Temp\\*\" > nul 2>&1"
"del /q \"%systemdrive%\\Windows\\Temp\\*\" > nul 2>&1"
"for /d %x in (\"%systemdrive%\\Windows\\Temp\\*\") do @rd /s /q \"%x\" > nul 2>&1"
"del /q \"%systemdrive%\\Windows\\TEMP\\*\" > nul 2>&1"
"for /d %x in (\"%systemdrive%\\Windows\\TEMP\\*\") do @rd /s /q \"%x\" > nul 2>&1"
"del /q \"%systemdrive%\\Windows\\temp\\*\" > nul 2>&1"
"for /d %x in (\"%systemdrive%\\Windows\\temp\\*\") do @rd /s /q \"%x\" > nul 2>&1"
"del /q \"%systemdrive%\\Program Files (x86)\\Temp\\*\" > nul 2>&1"
"del /q \"%systemdrive%\\Users\\%username%\\AppData\\Local\\D3DSCache\\*\" > nul 2>&1"
"for /d %x in (\"%systemdrive%\\Users\\%username%\\AppData\\Local\\CrashReportClient\\*\") do @rd /s /q \"%x\" > nul 2>&1"
"del /q \"%systemdrive%\\Users\\%username%\\Recent\\*\" > nul 2>&1"
"for /d %x in (\"%systemdrive%\\Users\\%username%\\Recent\\*\") do @rd /s /q \"%x\" > nul 2>&1"
"del /q \"%systemdrive%\\Users\\%username%\\AppData\\Local\\AMD\\*\" > nul 2>&1"
"for /d %x in (\"%systemdrive%\\Users\\%username%\\AppData\\Local\\AMD\\*\") do @rd /s /q \"%x\" > nul 2>&1"
"del /q \"%systemdrive%\\Users\\%username%\\AppData\\Local\\AMD_Common\\*\" > nul 2>&1"
"for /d %x in (\"%systemdrive%\\Users\\%username%\\AppData\\Local\\AMD_Common\\*\") do @rd /s /q \"%x\" > nul 2>&1"
"del /f /s /q %systemdrive%\\Users\\%username%\\AppData\\Local\\Microsoft\\Windows\\INetCookies\\ > nul 2>&1"
"del /f /s /q %systemdrive%\\Users\\%username%\\AppData\\Local\\Microsoft\\Windows\\History\\ > nul 2>&1"
"del /f /s /q %systemdrive%\\Users\\%username%\\AppData\\Local\\Microsoft\\Windows\\INetCache\\ > nul 2>&1"
"del /f /s /q %systemdrive%\\Windows\\Temp\\ > nul 2>&1"
"del /f /s /q %systemdrive%\\Windows\\Prefetch\\ > nul 2>&1"
"del /f /s /q %systemdrive%\\Temp\\ > nul 2>&1"
"del /f /s /q %systemdrive%\\*.l0g > nul 2>&1"
"del /f /s /q %systemdrive%\\*.tmp > nul 2>&1"
"del /f /s /q %systemdrive%\\*.old > nul 2>&1"
"del /f /s /q %systemdrive%\\*.bup > nul 2>&1"
"del /f /s /q %systemdrive%\\*.chk > nul 2>&1"
"del /f /s /q %systemdrive%\\*.temp > nul 2>&1"
"reg delete HKEY_LOCAL_MACHINE\\SYSTEM\\ControlSet001\\Services\\BEService /f"
"reg delete HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\BEService /f"
"reg delete HKEY_LOCAL_MACHINE\\SYSTEM\\ControlSet001\\Services\\EasyAntiCheat /f"
"del /f /s /q \"C:\\Program Files (x86)\\Common Files\\BattlEye\\BEService_fn.exe\""
"del /f /s /q \"C:\\Users\\%username%\\AppData\\Local\\AMD\\CN\\GameReport\\FortniteClient-Win64-Shipping.exe\\gpa.bin\""
"del /f /s /q \"C:\\Users\\%username%\\AppData\\Local\\AMD\\DxCache\\92b1da15789e5451b49097cdafa85ec0f45214d6b0df9e8d.bin\""
"del /f /s /q \"C:\\Users\\%username%\\AppData\\Local\\D3DSCache\\e4548a4577c56a84\\52264C4C-172F-41B9-91B8-7F0C3B1E9021_VEN_1002&DEV_67DF&SUBSYS_C580&REV_E7.lock\""
"del /f /s /q \"C:\\Users\\%username%\\AppData\\Local\\NVIDIA Corporation\\GfeSDK\\FortniteClient-Win64-Shipping_12856.l0g\""
"del /f /s /q \"C:\\Users\\%username%\\AppData\\Local\\Microsoft\\Windows\\History\\\""
"del /f /s /q \"C:\\Users\\%username%\\AppData\\Local\\Microsoft\\Windows\\INetCache\\\""
"del /f /s /q \"C:\\Users\\%username%\\AppData\\Local\\Temp\\\""
"del /f /s /q \"C:\\Windows\\Temp\""
"del /f /s /q \"C:\\Windows\\Prefetch\""
"del /f /s /q \"C:\\Temp\\\""
"del /f /s /q %systemdrive%\\*.l0g"
"del /f /s /q %systemdrive%\\*.tmp"
"del /f /s /q %systemdrive%\\*.chk"
"/q %systemdrive%\\*.dmp"
"del /f /s /q \"C:\\Users\\%username%\\AppData\\Local\\Temp\""
"del /f /s /q \"C:\\Windows\\Prefetch\""
"del /f /s /q \"C:\\Program Files (x86)\\EasyAntiCheat\""
"del /f /s /q \"C:\\Users\\%username%\\AppData\\Local\\EpicGamesLauncher\""
"del /f /s /q \"C:\\Program Files (x86)\\Common Files\\BattlEye\""
"del /f /s /q \"C:\\Users\\%username%\\AppData\\Local\\AMD\\CN\\GameReport\""
"del /f /s /q \"C:\\Users\\%username%\\AppData\\Local\\AMD\\cl.cache\""
"del /f /s /q \"C:\\Users\\%username%\\AppData\\Local\\AMD\\cl.cache\\x64\""
"del /f /s /q \"C:\\Users\\%username%\\AppData\\Local\\D3DSCache\\e4548a4577c56a84\""
"del /f /s /q \"C:\\Users\\%username%\\AppData\\Local\\NVIDIA Corporation\\GfeSDK\""
"del /f /s /q \"C:\\Users\\%username%\\AppData\\Local\\UnrealEngine\\5.0\""
"del /f /s /q \"C:\\Users\\%username%\\AppData\\Local\\CrashReportClient\""
"del /f /s /q \"C:\\Users\\%username%\\AppData\\Local\\FortniteGame\""
"reg delete \"HKLM\\SOFTWARE\\WOW6432Node\\EasyAntiCheat\" /f"
"reg delete \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\bam\\State\\UserSettings\\S-1-5-21-2532382528-581214834-2534474248-1001\\Device\\HarddiskVolume3\\Program Files\\Epic Games\\Fortnite\\FortniteGame\\Binaries\\Win64\\EasyAntiCheat\\EasyAntiCheat_Setup.exe: 73 D5 4B 11 8D 13 D5 01 00 00 00 00 00 00 00 00 00 00 00 00 02 00 00 00\" /f"
"reg delete \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\EasyAntiCheat\\Type: 0x00000010\" /f"
"reg delete \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\EasyAntiCheat\\Start: 0x00000003\" /f"
"reg delete \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\EasyAntiCheat\\ImagePath: \"%systemdrive%\\Program Files (x86)\\EasyAntiCheat\\EasyAntiCheat.exe\"\" /f"
"reg delete \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\EasyAntiCheat\\DisplayName: \"EasyAntiCheat\"\" /f"
"reg delete \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\EasyAntiCheat\\ObjectName: \"LocalSystem\"\" /f"
"reg delete \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\EasyAntiCheat\\Description: \"Provides integrated security and services for online multiplayer games.\" /f"
"del \"%localappdata%\\microsoft\\feeds\" /s /f /q"
"del \"%systemdrive%\\users\\%username%\\appdata\\local\\epicgameslauncher\\saved\\webcache\\cookies\""
"del \"%temp%\\getadmin.vbs\""
"del \"c:\\programdata\\microsoft\\search\\data\\applications\\windows\\edb.jcp\""
"del \"c:\\recovery\\ntuser.sys\""
"del \"c:\\system volume information\\indexervolumeguid\""
"del \"c:\\system volume information\\tracking.l0g\""
"del \"c:\\users\\%username%\\appdata\\locallow\\microsoft\\cryptneturlcache\""
"del \"c:\\users\\%username%\\appdata\\locallow\\microsoft\\cryptneturlcache\\content\""
"del \"c:\\users\\%username%\\appdata\\locallow\\microsoft\\cryptneturlcache\\metadata\\77ec63bda74bd0d0e0426dc8f8008506\""
"del \"c:\\users\\%username%\\appdata\\local\\crashdumps\\backgr~2.dmp\""
"del \"c:\\users\\%username%\\appdata\\local\\epicgameslauncher\\saved\\webcache\\cookies\""
"del \"c:\\users\\%username%\\appdata\\local\\microsoft\\feeds cache\""
"del \"c:\\users\\%username%\\appdata\\local\\microsoft\\windows\\webcache\\v01.chk\""
"del \"c:\\users\\%username%\\appdata\\local\\microsoft\\windows\\webcache\\v0100024.l0g\""
"del \"c:\\users\\%username%\\appdata\\local\\microsoft\\windows\\webcache\\webcac~1.dat\""
"del \"c:\\users\\%username%\\appdata\\local\\nvidia corporation\\gfesdk\\fortni~1.l0g\""
"del \"c:\\users\\%username%\\appdata\\local\\packages\\microsoft.windows.cortana_cw5n1h2txyewy\\appdata\\cachestorage\\caches~1.jfm\""
"del \"c:\\users\\%username%\\appdata\\local\\temp\\ecache.bin\""
"del \"c:\\users\\all users\\microsoft\\windows\\wer\\temp\\wer5cc2.tmp.xml\""
"del \"c:\\users\\all users\\microsoft\\windows\\wer\\temp\\wer95df.tmp.mdmp\""
"del \"c:\\users\\public\\shared files\""
"del \"c:\\windows\\cbstemp\\30780525_1668355464\""
"del \"c:\\windows\\inf\\e2xw10x64.pnf\""
"del \"c:\\windows\\inf\\ialpss2i_gpio2_skl.pnf\""
"del \"c:\\windows\\inf\\monitor.pnf\""
"del \"c:\\windows\\inf\\msports.pnf\""
"del \"c:\\windows\\inf\\ndisvirtualbus.pnf\""
"del \"c:\\windows\\inf\\netathr10x.pnf\""
"del \"c:\\windows\\inf\\netavpna.pnf\""
"del \"c:\\windows\\inf\\netsstpa.pnf\""
"del \"c:\\windows\\inf\\netvwifimp.pnf\""
"del \"c:\\windows\\inf\\rdpbus.pnf\""
"del \"c:\\windows\\inf\\usbxhci.pnf\""
"del \"c:\\windows\\inf\\wmiacpi.pnf\""
"del \"c:\\windows\\logs\\cbs\\cbs.l0g\""
"del \"c:\\windows\\system32\\wbem\\repository\\mapping1.map\""
"del \"c:\\windows\\system32\\wbem\\repository\\writable.tst\""
"del \"c:\\windows\\temp\\206f3fdc-b1a8-4fd6-bdb8-6cfe76122873\""
"del \"c:\\windows\\temp\\6e04ef32-0387-48b1-b812-ac2bba90a8d0\""
"del /q /f %windir%\\kb*.l0g"
"del /q /f /a /s \"c:\\users\\%username%\\appdata\\local\\iconcache.db\""
"del /q /f /a /s \"c:\\users\\%username%\\appdata\\local\\updater.l0g\""
"del /f \"c:\\programdata\\microsoft\\windows\\devicemetadatacache\\dmrc.idx\""
"del /f \"c:\\system volume information\\tracking.l0g\""
"del /f \"c:\\users\\%username%\\appdata\\local\\ac\\inetcookies\\ese\\container.dat\""
"del /f \"c:\\users\\%username%\\appdata\\local\\microsoft\\onedrive\\logs\\common\\devicehealthsummaryconfiguration.ini\""
"del /f \"c:\\users\\%username%\\appdata\\local\\microsoft\\vault\\userprofileroaming\\latest.dat\""
"del /f \"c:\\users\\%username%\\appdata\\local\\unrealengine\\4.23\\saved\\config\\windowsclient\\manifest.ini\""
"del /f \"c:\\users\\%username%\\ntuser.ini\""
"del /f \"c:\\windows\\win.ini\""
"del /f /q \"%userprofile%\\recent\\*.*\""
"del /f /s /q \"%appdata%\\roaming\\easyanticheat\\*.*\""
"del /f /s /q \"%systemdrive%paint\\users\\%username%\\appdata\\roaming\\vstelemetry\\*.*\""
"del /f /s /q \"%systemdrive%\\desktop.ini\\*.*\""
"del /f /s /q \"%systemdrive%\\intel\\*.*\""
"del /f /s /q \"%systemdrive%\\msocache\\{71230000-00e2-0000-1000-00000000}\\setup.dat\\*.*\""
"del /f /s /q \"%systemdrive%\\program files (x86)\\easyanticheat\\*.*\""
"del /f /s /q \"%systemdrive%\\program files (x86)\\easyanticheat\\easyanticheat.sys\""
"del /f /s /q \"%systemdrive%\\programdata\\electronic arts\\*\""
"del /f /s /q \"%systemdrive%\\programdata\\electronic arts\\ea services\\license\\*\""
"del /f /s /q \"%systemdrive%\\programdata\\electronic arts\\ea services\\license\\*.*\""
"del /f /s /q \"%systemdrive%\\programdata\\microsoft\\datamart\\paidwifi\\networkscache\\*.*\""
"del /f /s /q \"%systemdrive%\\programdata\\microsoft\\datamart\\paidwifi\\networkscache\\*.*\""
"del /f /s /q \"%systemdrive%\\programdata\\microsoft\\windows\\wer\\temp\\*.*\""
"del /f /s /q \"%systemdrive%\\programdata\\microsoft\\windows\\wer\\temp\\*.*\""
"del /f /s /q \"%systemdrive%\\system volume information\\*.*\""
"del /f /s /q \"%systemdrive%\\temp\\*.*\""
"del /f /s /q \"%systemdrive%\\users\\%username%\\appdata\\local\\microsoft\\feeds\\*.*\""
"del /f /s /q \"%systemdrive%\\users\\%username%\\appdata\\local\\microsoft\\windows\\history\\history.ie5\\*.*\""
"del /f /s /q \"%systemdrive%\\users\\%username%\\appdata\\local\\microsoft\\windows\\history\\history.ie5\\*.*\""
&"reg delete \"hklm\\software\\microsoft\\windows\\currentversion\\appmodel\\staterepository\\cache\\package\\data\\182\" /f"
"netsh advfirewall reset > nul 2>&1"